[package]
name = "S3parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
indicatif = "0.17.8"
itertools = "0.13.0"
polars = { version = "0.41.3", features = ["lazy"] }
regex = "1.10.6"
